language: cpp
before_script:
- git clone https://github.com/google/googletest.git
- cd googletest        # Main directory of the cloned repository.
- mkdir build          # Create a directory to hold the build output.
- cd build
- cmake ..             # Generate native build scripts for GoogleTest.
- sudo make install    # Install in /usr/local/ by default
- sudo apt-get install libboost-test-dev -y
- echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list
- sudo apt-get update -qq
script:
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
