language: cpp
before_script:
- sudo apt-get install libboost-test-dev -y
- echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list
- sudo apt-get update -qq
script:
- cmake ./homeworks/homework1/Task1
- cmake --build ./homeworks/homework1/Task1
- cmake --build ./homeworks/homework1/Task1 --target test
- cmake --build ./homeworks/homework1/Task1 --target package
